services:
  # Сервис приложения (PHP-FPM + Nginx)
  app:
    image: 'webdevops/php-nginx:8.2'
    restart: unless-stopped
    ports:
      - "8080:80" # Изменен порт, чтобы не конфликтовать с фронтендом
    volumes:
      - .:/app
    working_dir: /app
    # Явно указываем Nginx, где находится публичная папка Laravel
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    # Подключаем остальные переменные из .env файла
#    env_file:
#      - .env

  # Сервис базы данных (PostgreSQL)
  db:
    image: 'postgres:15'
    restart: unless-stopped
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - 'locsy_postgres_data:/var/lib/postgresql/data'
    # Переменные для создания базы данных
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # Сервис фронтенда (Quasar + Nginx)
  frontend:
    build:
      context: ../locsy-spa-quasar # Путь к вашему Quasar-проекту
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80" # Фронтенд будет доступен на порту 8000
    depends_on:
      - app

# Docker Volume для сохранения данных БД
volumes:
  locsy_postgres_data:
    driver: local
